### ISSUE TITLE
Diff between SLS and other STL files?

### ISSUE THREAD

**Issue by theopensourcerer** [AxMod3DPrint/Drakon-Extruder#4]
As above, what's the difference between the two sets of drawings? I started printing some of the parts in PETG last night but am not sure if I am using the right files - I used the SLS parts.

Thanks

**Comment by ViperWorx** [comment]
SLS has tighter tolerances and is designed to be used when SLS Printing the parts.

**Comment by theopensourcerer** [comment]
Opps - thanks. I better start again then ;-)
