### ISSUE TITLE
The small gear is missing from the step file. 

### ISSUE THREAD

**Issue by AgelosL** [AxMod3DPrint/Drakon-Extruder#6]
Hello. I was looking in the step file and noticed that the small gear is not present. I want to use some existing gears I got from an inkjet printer but I cannot make the necessary modifications unless both gears are in there. I would appreciate it if you were to include it in a new commit.

Thanks for your work in Drakon extruder and thanks in advance for taking the time to help.

Angelo

**Comment by ViperWorx** [comment]
Hi,

Thanks for letting me know, I'll get the Step files updated later today

**Comment by AgelosL** [comment]
Thanks!

**Comment by ViperWorx** [comment]
Hi there,

All parts have been uploaded individually and are at the current version.
